name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    container: ryuichiueda/ubuntu20.04-ros2:latest #上田先生のコンテナを使用
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        shell: bash
        run: |
          apt-get update
          apt-get install -y psmisc
      - name: Setup ROS2 Workspace
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash || source /opt/ros/foxy/setup.bash
          colcon build
      - name: build
        shell: bash
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws
          colcon build
          source install/setup.bash
      - name: Run Tests
        shell: bash
        run:
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/test.bash /root
