    name: test
    on: push
    jobs:
      test:
        runs-on: ubuntu-20.04
        strategy:
          matrix:
            python-version: ["3.8"]
    
        steps:
        - uses: actions/checkout@v3
        - name: All test
          run: 
            rsync -av ./ /root/ros2_ws/src/mypkg/
            cd /root/ros2_ws
            bash -exv ./src/mypkg/test/test.bash /root
            
