    name: test
    on: push
    jobs:
      test:
        runs-on: ubuntu-20.04
        container: ryuichiueda/ubuntu22.04-ros2:latest
        steps:
          - uses: actions/checkout@v2
          - name: Install ROS 2 Foxy
            run: |
              # ROS 2 Foxyの依存関係をインストール
              sudo apt update
              sudo apt install -y curl gnupg lsb-release
              sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo tee /etc/apt/trusted.gpg.d/ros.asc
              sudo sh -c 'echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
              sudo apt update
              sudo apt install -y ros-humble-desktop
              sudo apt install -y python3-colcon-common-extensions

              # ROS 2 のセットアップ
              source /opt/ros/humble/setup.bash
            shell: bash  # bashシェルを指定
          - name: Sync files and build workspace
            run: |
              rsync -av ./ /root/ros2_ws/src/mypkg/
              cd /root/ros2_ws
              colcon build
              source install/setup.bash
            shell: bash  # bashシェルを指定
          - name: Run test script
            run: |
              bash -exv ./src/mypkg/test/test.bash /root
            shell: bash  # bashシェルを指定
