    name: test
    on: push
    jobs:
      test:
        runs-on: ubuntu-20.04
        container: ryuichiueda/ubuntu22.04-ros2:latest
        steps:
        - uses: actions/checkout@v2
        - name: All test
          run: |
            source /opt/ros/foxy/setup.bash
            rsync -av ./ /root/ros2_ws/src/mypkg/
            cd /root/ros2_ws
            colcon build
            source install/setup.bash
            bash -exv ./src/mypkg/test/test.bash /root
            shell: bash
